name: Despliegue en servidor
on:
  push:
    branches:
      - master

jobs:
  Deploy2VPS:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Despliegue en servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/consorcioaccion.com/API_real_estat_agency
          git stash
          git pull
          pip install -r requirements.txt
          echo "nicolas23" | sudo -S systemctl restart uvicorn.service
