name: Despliegue en servidor

on:
  push:
    branches:
      - master

jobs:
  despliegue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Despliegue en servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/toorble.com/API_real_estat_agency
          git pull
          sudo systemctl restart uvicorn.service